apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cars-deployment
spec:
  selector:
    matchLabels:
      app: cars_app
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cars_app
    spec:
      containers:
      - name: app-server
        image:  tombatchelor/cars:1.32-leak
        ports:
        - name: cars-app-port
          containerPort: 8080
        env:
        - name: ZIPKIN_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: zipkin-config
              key: zipkin.endpoint
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: secret-key
        livenessProbe:
          httpGet:
            path: /Cars_Sample_App/public/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "256M"
          limits:
            memory: "768M"
