global:
  evaluation_interval: 30s
  scrape_interval: 30s

remote_write:
- url: http://proxy.observe.svc.cluster.local:2001/prometheus/write
  remote_timeout: 30s

scrape_configs:
- job_name: tomcat
  metrics_path: /Cars_Sample_App/metrics/
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: k8s_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: k8s_pod_name
  - source_labels: [__address__]
    action: replace
    regex: ([^:]+)(?::\d+)?
    replacement: ${1}:8080
    target_label: __address__
  - source_labels: [__meta_kubernetes_pod_label_app]
    action: keep
    regex: cars_app
