apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanuptest
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: tombatchelor/carscleanup:4.2
            imagePullPolicy: Always
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cred
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-cred
                  key: secret-key
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: aws
                  key: bucket.name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: database.password
          restartPolicy: OnFailure
