apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: marshaller
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: apply-data
            image: tombatchelor/demo_marshaller:3.6
            env:
            - name: COLLECTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: marshaller
                  key: collector.url
            - name: CUSTOMER_ID
              valueFrom:
                configMapKeyRef:
                  name: marshaller
                  key: customer.id
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: observe-key
                  key: token
            - name: GIT_ROOT
              valueFrom:
                configMapKeyRef:
                  name: jenkins-env
                  key: git.root
            volumeMounts:
            - name: git-key
              mountPath: /keys
          restartPolicy: OnFailure
          volumes:
          - name: git-key
            secret:
              secretName: git-key
  
