apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: virtual-host-ingress
  namespace: default
spec:
  rules:
  - host: cars.cars.com
    http:
      paths:
      - backend:
          serviceName: cars-web
          servicePort: 80
