apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cars-loadgen-deployment
spec:
  selector:
    matchLabels:
      app: cars_loadgen
  replicas: 1
  template:
    metadata:
      labels:
        app: cars_loadgen
    spec:
      containers:
      - name: jmeter
        image: tombatchelor/carsloadgen:3.2
        imagePullPolicy: Always
